micronaut:
  application:
    name: user-service-demo
  server:
    port: 8086
  router:
        static-resources:
            swagger:
                paths: classpath:META-INF/swagger
                mapping: /swagger/**
netty:
  default:
    allocator:
      max-order: 3
    

r2dbc:
  datasources:
    default:
      driver: mysql
      host: localhost
      port: 3306
      database: todo-services-sample
      username: todo-svc-user
      password: ABC123abc

mongodb:
  uri: mongodb://localhost:27017/todo-services-demo
  
  
consul:
  client:
    defaultZone: ${CONSUL_HOST:localhost}:${CONSUL_PORT:8500}
    registration:
      enabled: true