micronaut:
  application:
    name: user-service-demo
  server:
    port: 8086
  security:
    enabled: true
    reject-not-found: false
    redirect:
      enabled: false
    authentication: session
    token:
      jwt:
        generator:
          access-token:
            expiration: 60
          refresh-token:
            secret: "${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThisSecretForANewOne}"
  caches:
   refresh-token: 
     charset: 'UTF-8'
     expire-after-write: 5m
  router:
        static-resources:
            swagger:
                paths: classpath:META-INF/swagger
                mapping: /swagger/**
netty:
  default:
    allocator:
      max-order: 3
    

r2dbc:
  datasources:
    default:
      driver: mysql
      host: localhost
      port: 3306
      database: todo-services-sample
      username: todo-svc-user
      password: ABC123abc

mongodb:
  uri: mongodb://localhost:27017/todo-services-demo
  
