micronaut:
  application:
    name: todoServiceDemo
  caches:
    todo-cache:
      maximum-size: 20
netty:
  default:
    allocator:
      max-order: 3
      
to-do:
  config:
    title-prefix: TODO-
    title-max-length: 100
    description-max-length: 250
    expiry-duration: 24h
  prop-a: value-a
  prop-b: value-b
  prop-c: ${to-do.prop-a},${to-do.prop-b},${to-do.prop-x:default-x}  
  service:
    database: false
    
user-service:
  host: localhost
  port: 8086
  url: http://${user-service.host}:${user-service.port}
  
micronaut:
  http:
    client:
      read-timeout: 5s
      pool:
        enabled: true
        max-connections: 50
logger:
  levels:
    com.learn.mn.controllers.V1TodoController: INFO
    
    

  