micronaut:
  application:
    name: todoServiceDemo
  caches:
    todo-cache:
      maximum-size: 20
netty:
  default:
    allocator:
      max-order: 3
      
to-do:
  config:
    title-prefix: TODO-
    title-max-length: 100
    description-max-length: 250
    expiry-duration: 24h
  prop-a: value-a
  prop-b: value-b
  prop-c: ${to-do.prop-a},${to-do.prop-b},${to-do.prop-x:default-x}  
  service:
    database: true
    
user-service:
  host: localhost
  port: 8086
  url: http://${user-service.host}:${user-service.port}
  
micronaut:
  http:
    client:
      read-timeout: 5s
      pool:
        enabled: true
        max-connections: 50
logger:
  levels:
    com.learn.mn.controllers.V1TodoController: INFO

endpoints:
  greetings:
    enabled: true
    sensitive: false
  env:
    enabled: true
    sensitive: false
  stop:
    enabled: true
    sensitive: false
  loggers:
    enabled: true
    sensitive: false
  routes:
    enabled: true
    sensitive: false
  refresh:
    enabled: true
    sensitive: false
  metrics:
    enabled: true
    sensitive: false
  health:
    enabled: true
    sensitive: false
    details-visible: ANONYMOUS
    #status:
    #  http-mapping: 
        # DOWN: 200
  info:
    enabled: true
    sensitive: false
    config:
      enabled: true
    git:
       enabled: true
  beans:
    enabled: true
    sensitive: false
    
info:
   todo:
      sample-key:sample-value
      
datasources:
  default:
    dialect: MYSQL
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/todo-services-sample
    username: todo-svc-user
    password: ABC123abc
    
jackson:
    serialization:
        writeDatesAsTimestamps: false

    

  